AppSyncRealTimeClient.podspec
CHANGELOG.md

Release 1.1.4 - Carthage users

---

AppSyncRealTimeClient.podspec
CHANGELOG.md

Release 1.1.5

---

AppSyncRealTimeClient.podspec
CHANGELOG.md

version bump 1.2.0

---

.gitignore
AppSyncRealTimeClientIntegrationTests/README.md
AppSyncRealTimeClientIntegrationTests/Support/schema.graphql
CHANGELOG.md

chore: Fix integration tests instructions and add test schema to support files

---

AppSyncRealTimeClient.podspec
CHANGELOG.md

chore: prep 1.2.1 release

---

AppSyncRealTimeClient.podspec
CHANGELOG.md
build-support/setup_private_specs.sh

- chore: Add setup_private_specs support script to enable easier local dev
**Note: Releasing this as a minor version bump to highlight the Licensing change, although technically there is no functionality change.**

chore: prep 1.4.0 release

---

Cartfile

https://github.com/aws-amplify/aws-appsync-realtime-client-ios/issues/23

chore: Update cartfile

---

AppSyncRealTimeClient.podspec
CHANGELOG.md

chore: prep 1.4.1 release

---

AppSyncRealTimeClient/Support/CountdownTimer.swift
AppSyncRealTimeClientTests/Support/CountdownTimerTests.swift
CHANGELOG.md

fix: Fix data races in CountdownTimer

---

AppSyncRealTimeClient.podspec
CHANGELOG.md

chore: prep 1.4.2 release

---

Package.resolved
Package.swift

Add a Package.swift so that the lib can be used with SPM.

Swift Package support

---

AppSyncRealTimeClient.podspec
AppSyncRealTimeClient/Info.plist
CHANGELOG.md
Cartfile

chore: Prep release 1.4.4

---

AppSyncRealTimeClient.podspec
AppSyncRealTimeClient/Info.plist
CHANGELOG.md

chore: prep 1.5.0 release

---

.github/CODEOWNERS

chore: Added code owners for github

---

AppSyncRealTimeClient.podspec
AppSyncRealTimeClient/Info.plist
CHANGELOG.md

chore: Prep 1.6.0 release

---

.circleci/config.yml
Gemfile.lock

chore: fix CI issues - xcode 13.2.1

---

AppSyncRealTimeClient.podspec
AppSyncRealTimeClient/Info.plist
CHANGELOG.md

chore: Prep 1.7.0 release

---

AppSyncRealTimeClientTests/ConnectionProvider/ConnectionProviderHandleErrorTests.swift

fix: Add missing @available check in tests

---

.circleci/config.yml

chore: update config.yml

---

AppSyncRealTimeClient.podspec
AppSyncRealTimeClient/Info.plist

chore: Prep 1.9.1 release

---

AppSyncRealTimeClient.podspec
AppSyncRealTimeClient/Info.plist
CHANGELOG.md

chore: Prep 1.10.0 release

---

AppSyncRealTimeClient/Interceptor/OIDCAuthInterceptorAsync.swift
AppSyncRealTimeClient/Support/OIDCAuthProviderAsync.swift

add support for async oidc interceptor

feat: add support for async oidc interceptor

---

AppSyncRealTimeClient.podspec
AppSyncRealTimeClient/Info.plist
CHANGELOG.md

chore: Prep 2.1.0 release

---

AppSyncRealTimeClient.podspec
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider+Websocket.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnectionAsync/RealtimeConnectionProviderAsync+ConnectionInterceptableAsync.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnectionAsync/RealtimeConnectionProviderAsync+MessageInterceptableAsync.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnectionAsync/RealtimeConnectionProviderAsync+StaleConnection.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnectionAsync/RealtimeConnectionProviderAsync+Websocket.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnectionAsync/RealtimeConnectionProviderAsync.swift
AppSyncRealTimeClient/ConnectionProvider/ConnectionProviderFactory.swift
AppSyncRealTimeClient/ConnectionProvider/InterceptableConnectionAsync.swift
AppSyncRealTimeClient/ConnectivityMonitor/ConnectivityMonitor.swift
AppSyncRealTimeClient/ConnectivityMonitor/ConnectivityPath.swift
AppSyncRealTimeClient/Info.plist
AppSyncRealTimeClient/Interceptor/OIDCAuthInterceptorAsync.swift
AppSyncRealTimeClient/Support/AppSyncLogger.swift
AppSyncRealTimeClient/Support/OIDCAuthProviderAsync.swift
AppSyncRealTimeClient/Support/TaskQueue.swift
AppSyncRealTimeClientTests/ConnectionProvider/ConnectionProviderHandleErrorTests.swift
CHANGELOG.md
Package.swift

chore: Prep 2.1.0 merge main to release

---

AppSyncRealTimeClient.podspec
AppSyncRealTimeClient/Info.plist
CHANGELOG.md

chore: Prep 2.1.1 release

---

AppSyncRealTimeClient/Websocket/Starscream/StarscreamAdapter.swift

chore: Add no store for the cache in urlsession

---

AppSyncRealTimeClient.podspec
AppSyncRealTimeClient/Info.plist
CHANGELOG.md

chore: Prep 3.0.0 release

---

.github/CODEOWNERS
AppSyncRealTimeClient.podspec
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnectionAsync/RealtimeConnectionProviderAsync.swift
AppSyncRealTimeClient/ConnectionProvider/ConnectionProviderFactory.swift
AppSyncRealTimeClient/Info.plist
AppSyncRealTimeClient/Support/TaskQueue.swift
AppSyncRealTimeClient/Websocket/AppSyncWebsocketProvider.swift
AppSyncRealTimeClient/Websocket/Starscream/StarscreamAdapter.swift
AppSyncRealTimeClientIntegrationTests/AppSyncRealTimeClientAsync/AppSyncRealTimeClientAsyncFailureTests.swift
AppSyncRealTimeClientIntegrationTests/AppSyncRealTimeClientAsync/AppSyncRealTimeClientAsyncIntegrationTests.swift
AppSyncRealTimeClientIntegrationTests/AppSyncRealTimeClientFailureTests.swift
AppSyncRealTimeClientIntegrationTests/AppSyncRealTimeClientIntegrationTests.swift
AppSyncRealTimeClientIntegrationTests/AppSyncRealTimeClientTestBase.swift
AppSyncRealTimeClientIntegrationTests/StarscreamAdapterTests.swift
AppSyncRealTimeClientTests/ConnectionProvider/ConnectionProviderAsync/RealtimeConnectionProviderAsyncTestBase.swift
AppSyncRealTimeClientTests/ConnectionProvider/ConnectionProviderHandleErrorTests.swift
AppSyncRealTimeClientTests/ConnectionProvider/RealtimeConnectionProviderTestBase.swift
AppSyncRealTimeClientTests/Mocks/MockWebsocketProvider.swift
CHANGELOG.md
Gemfile.lock
Pods/Pods.xcodeproj/project.pbxproj

chore: Prep 3.0.0 merge main to release

---

AppSyncRealTimeClient.xcodeproj/project.pbxproj
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider+Websocket.swift

*Issue #, if available:* None
*Description of changes:* Fix build warnings in aws-appsync-realtime-client-ios

chore: fix build warnings

---

CHANGELOG.md

chore: update CHANGELOG.md [skip ci]

---

AppSyncRealTimeClient.podspec
AppSyncRealTimeClient/Info.plist
CHANGELOG.md

chore: Prep 3.1.0 release

---

.circleci/config.yml
fastlane/Fastfile

- read CocoaPods Trunk Token from AWS secret with OIDC

ci: read CocoaPods trunk token from AWS secret

---

.github/workflows/kickoff-release.yml

- add kickoff release workflow

ci: add kickoff release workflow

---

README.md

n/a
Updates README to include info block explaining where to open issues.

chore: update readme with info block specifying where to open issues

---

.github/workflows/deploy-pods.yml
.github/workflows/kickoff-release.yml
fastlane/Fastfile

- update release workflow to do release process on main branch

chore(ci): update release workflow

---

.github/workflows/kickoff-release.yml
.gitignore

- submit kickoff release commit with podspec changes

chore(ci): submit kickoff release commit with podspec changes

---

AppSyncRealTimeClient.podspec

Reverts aws-amplify/aws-appsync-realtime-client-ios#155

Revert "chore: release commit for 3.2.0"
