AppSyncRealTimeClient.podspec
AppSyncRealTimeClient.xcodeproj/project.pbxproj
AppSyncRealTimeClient/Connection/AppSyncConnection/AppSyncSubscriptionConnection+Connection.swift
AppSyncRealTimeClient/Connection/AppSyncConnection/AppSyncSubscriptionConnection.swift
AppSyncRealTimeClient/Connection/SubscriptionConnection.swift
AppSyncRealTimeClient/Connection/SubscriptionItem.swift
AppSyncRealTimeClientTests/Connection/AppSyncSubscriptionConnectionTests.swift
CHANGELOG.md

The subscription api supports passing in a data in variable with nill value. But the new subscription realtime connection code was not setup to
receive that value. This change fixes that.

Made the variable data in subscription optional

---

AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider.swift
AppSyncRealTimeClient/Interceptor/RealtimeGatewayURLInterceptor.swift
AppSyncRealTimeClient/Websocket/Starscream/StarscreamAdapter.swift

*Issue [#328](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/328)
This PR moves the calls to websocket into write into a separate queue so that the interceptors wont block any other queue unintentionaly.

Fix subscription threading issue

---

cartfile

When installling 1.1.1, the pod issue goes away, but now there's 
```
/Users/x/temp/appsyncRealTimeCarthageTest/Carthage/Checkouts/aws-appsync-realtime-client-ios/AppSyncRealTimeClient/Websocket/Starscream/StarscreamAdapter+Delegate.swift:9:8: error: no such module 'Starscream'
import Starscream
```
I suspect this repo needs it's dependency on starscream via the cartfile

adding cartfile for dependency on starscream

---

.gitignore
AppSyncRealTimeClient.podspec
AppSyncRealTimeClient.xcodeproj/project.xcworkspace/contents.xcworkspacedata
AppSyncRealTimeClient.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
AppSyncRealTimeClient.xcworkspace/contents.xcworkspacedata
AppSyncRealTimeClient.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Cartfile
Podfile
Podfile.lock
Pods/Manifest.lock
cartfile

Some changes made to enable carthage users
- checking in the workspace file
- decided to take patch version dependency on Starscream (don't think this is needed since pod lock is already on 3.0.6), may revert this change after some testing.

Add files required for Carthage users

---

Cartfile

The Cartfile is needed due to this repo being managed by Cocoapods. Carthage users that install via a Cartfile which points to this repo requires a Cartfile to know which dependencies to additionally pull in, otherwise the resolved dependency only contains AppSyncRealTimeClient.
With the Cartfile that specifies the Starscream in this repository, then Carthage users with a Cartfile that pulls this repository in will additionally pull in Starscream, as seen in the Cartfile.resolved file.

Adding Cartfile with Starscream dependency

---

AppSyncRealTimeClient.podspec
Podfile
Podfile.lock
Pods/Manifest.lock
Pods/Pods.xcodeproj/project.pbxproj
Pods/Starscream/README.md
Pods/Starscream/Sources/Starscream/WebSocket.swift
Pods/Target Support Files/Starscream/Starscream-Info.plist

https://github.com/aws-amplify/aws-appsync-realtime-client-ios/issues/16
Add optimistic dependency on Starscream 3.1.0
related: https://github.com/daltoniam/Starscream/releases

Upgrade Starscream to ~> 3.1.0

---

AppSyncRealTimeClient/Connection/SubscriptionItem.swift
CHANGELOG.md

Make SubscriptionItem.init public to allow for `SubscriptionConnection` mocks in other packages to new `SubscriptionItem`s.

fix: Make SubscriptionItem.init public

---

AppSyncRealTimeClient.xcodeproj/xcshareddata/xcschemes/AppSyncRealTimeClientIntegrationTests.xcscheme
AppSyncRealTimeClient/Connection/AppSyncConnection/AppSyncSubscriptionConnection+ErrorHandler.swift
AppSyncRealTimeClient/Connection/AppSyncConnection/AppSyncSubscriptionConnection.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider+StaleConnection.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider+Websocket.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider.swift
AppSyncRealTimeClient/ConnectionProvider/ConnectionProviderFactory.swift
AppSyncRealTimeClient/Support/AppSyncJSONHelper.swift
AppSyncRealTimeClient/Support/CountdownTimer.swift
AppSyncRealTimeClient/Support/SubscriptionConstants.swift
AppSyncRealTimeClient/Websocket/Starscream/StarscreamAdapter.swift
AppSyncRealTimeClientIntegrationTests/AppSyncRealTimeClientIntegrationTests.swift

We received reports of a crash in the StarScreamAdaptor on the line `socket?.write(string: message)`.
Running the integ tests with ThreadSanitizer confirmed my suspicions that the disconnect flow had a race condition: disconnecting sets `socket` to `nil`, which could happen after we check for the existence of `socket` in the null unwrap.
This change:
- Expands use of the connection queue for concurrency protection
- Privatizes a few members of `RealtimeConnectionProvider`
- Normalized initialization to all take place in `init` instead of being spread across `init` and the property declaration
- Adds concurrency protection to the integ test status assertions to avoid spurious race conditions
- Adds the unit tests as a test target of the integ tests so they will always run
- Updates …

fix: Fix race condition in disconnect; protect status & write access

---

AppSyncRealTimeClient.podspec
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider+StaleConnection.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider+Websocket.swift
AppSyncRealTimeClient/Info.plist
AppSyncRealTimeClientIntegrationTests/AppSyncRealTimeClientIntegrationTests.swift
CHANGELOG.md

Version bump to 1.4.3, including Info.plist that was not previously updated. Also includes more copyright year updates where SwiftFormat found them.

chore: Prep 1.4.3 release

---

.gitignore
AppSyncRealTimeClient.xcodeproj/xcshareddata/xcschemes/AppSyncRealTimeClient.xcscheme
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider+StaleConnection.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider+Websocket.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider.swift
AppSyncRealTimeClient/Support/CountdownTimer.swift
AppSyncRealTimeClientTests/ConnectionProvider/ConnectionProviderStaleConnectionTests.swift
AppSyncRealTimeClientTests/ConnectionProvider/ConnectionProviderTests.swift
AppSyncRealTimeClientTests/Support/CountdownTimerTests.swift

The data race occurred when the countdown timer was first created and at the same time it was invalidated. The underlying `workItem: DispatchWorkItem` was being set and canceled at the same time. The scenario is
1. Connecting to the websocket
2. When connected, send the connect init message and start the timer
3. When receiving the connection ack message from the websocket (or any other messages for that matter at `handleResponse(_ response)`), then reset the timer. The timer is reset on every message to ensure the freshness of the connection. Whenever there's a keep-alive or any message, the stale connection timer is reset. If 5 minutes elapsed and the timer fires, it disconnects the websocket and signals the subscriptions to attempt the …

fix: data race in CountdownTimer

---

AppSyncRealTimeClient.xcodeproj/project.pbxproj
AppSyncRealTimeClient/AWSAppSyncRealTimeClient.swift
AppSyncRealTimeClient/Support/AppSyncLogger.swift
AppSyncRealTimeClientIntegrationTests/AppSyncRealTimeClientTestBase.swift

Allow the logging level to be configurable allows the consumers of this package (API Plugin and AppSync SDK) to set it through its log level. In Amplify, when the developer sets `Amplify.Logging.logLevel`, this can be propagated to `AppSyncRealTimeClient.logLevel` when the plugins are configured. Since the intention is to propagate the log levels from Amplify, they are identical to the ones defined in Amplify.Logging category https://github.com/aws-amplify/amplify-ios/blob/main/Amplify/Categories/Logging/LogLevel.swift
```swift
enum LogLevel: Int {
case error
case warn
case info
case debug
case verbose
}
```
- errors is the default log level (also is Amplify's)
- the log level can be set with `AppSyncRealTimeClient.logLevel = .verbose` by …

feat: Allow setting log level

---

AppSyncRealTimeClient.podspec
AppSyncRealTimeClient/Info.plist
CHANGELOG.md

Reference to previous prep PR https://github.com/aws-amplify/aws-appsync-realtime-client-ios/pull/70

chore: Prep 1.8.0 release

---

AppSyncRealTimeClient.xcodeproj/project.pbxproj
AppSyncRealTimeClient/Connection/AppSyncConnection/AppSyncSubscriptionConnection+Connection.swift
AppSyncRealTimeClient/Connection/AppSyncConnection/AppSyncSubscriptionConnection+ErrorHandler.swift
AppSyncRealTimeClient/Connection/AppSyncConnection/AppSyncSubscriptionConnection.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider+StaleConnection.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider+Websocket.swift
AppSyncRealTimeClientIntegrationTests/AppSyncRealTimeClientFailureTests.swift
AppSyncRealTimeClientIntegrationTests/AppSyncRealTimeClientTestBase.swift
AppSyncRealTimeClientTests/Connection/AppSyncSubscriptionConnectionTests.swift

The caller of a subscription should only receive the `.failed` event once. A `.failed` event to the caller indicates that the subscription is in terminal state. In AppSync SDK, this event is propagated back to the caller in the resultHandler. In APIPlugin, this is in the completionListener. Data/Connection events are propagated in a different handler (statusHandler, progressHandler). 
The bug is that the subscription will send multiple `.failed` events in a few scenarios. 
1. Subscription level messages (messages with the exact subscription ID) will be sent to all subscriptions and filtered out by other subscriptions. Errors are handled by sending the `.failed` event.
2. Connection level messages will be sent to all subscriptions, the …

fix: Subscription failed event should be terminal event

---

AppSyncRealTimeClient.podspec
AppSyncRealTimeClient/Info.plist
CHANGELOG.md

Reference (previous prep PR): https://github.com/aws-amplify/aws-appsync-realtime-client-ios/pull/72

chore: Prep 1.8.1 release

---

AppSyncRealTimeClient.xcodeproj/project.pbxproj
AppSyncRealTimeClient.xcodeproj/xcshareddata/xcschemes/AppSyncRealTimeClient.xcscheme
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider+StaleConnection.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider.swift
AppSyncRealTimeClient/ConnectivityMonitor/ConnectivityMonitor.swift
AppSyncRealTimeClient/ConnectivityMonitor/ConnectivityPath.swift
AppSyncRealTimeClientTests/ConnectionProvider/ConnectionProviderStaleConnectionTests.swift
AppSyncRealTimeClientTests/ConnectionProvider/RealtimeConnectionProviderTestBase.swift
AppSyncRealTimeClientTests/ConnectivityMonitor/ConnectivityMonitorTests.swift
AppSyncRealTimeClientTests/Mocks/MockConnectivityMonitor.swift

When there is an intermittent network issue while the websocket is connected, the subscriptions will stop receiving events and take around 5 minutes to reconnect once the stale connection timeout occurs. During these 5 minutes, the network may have gone back online leaving a window of silence despite mutations being sent successfully. This PR adds a connectivity monitor to listen to network changes. When the network goes down while connected, it will mark it as a stale connection, and when it goes back up, it will attempt to reconnect.
- Add ConnectivityMonitor (structure copied from @brennanMKE's [ConnectivityKit](https://github.com/brennanMKE/ConnectivityKit) that uses [NWPathMonitor](https://developer.apple.com/documentation/network/nwp …

feat: Attempt to reconnect on connectivity

---

AppSyncRealTimeClient.podspec
AppSyncRealTimeClient/Info.plist
CHANGELOG.md

Reference of previous release https://github.com/aws-amplify/aws-appsync-realtime-client-ios/pull/75

chore: Prep 1.9.0 release

---

AppSyncRealTimeClient.xcodeproj/project.pbxproj
AppSyncRealTimeClient/Connection/AppSyncConnection/AppSyncSubscriptionConnection+ErrorHandler.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider+Websocket.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProviderResponse.swift
AppSyncRealTimeClientTests/Connection/AppSyncSubscriptionConnectionErrorHandlerTests.swift
AppSyncRealTimeClientTests/ConnectionProvider/AppSyncRealTimeConnection/RealTimeConnectionProviderResponseTests.swift
AppSyncRealTimeClientTests/ConnectionProvider/ConnectionProviderHandleErrorTests.swift
AppSyncRealTimeClientTests/Mocks/MockWebsocketProvider.swift

The LimitExceeded error is received when AppSync throttles the client for making too many subscription requests:
```
{"type":"error","payload":{"errors":{"errorType":"LimitExceededError","message":"Rate limit exceeded"}}}
```
This happens once the rate of subscribes has exceeded the limit on AppSync. Since 100 subscriptions can be established successfully, a loop with 200 or more subscriptions requests will reproduce this.
Consider the current flow
```mermaid
flowchart
A[AppSync] --> |sends LimitExceeded| B[Websocket client];
B --> |convert to ConnectionProviderError.other| C1[Subscription1 - subscribed];
B --> |convert to ConnectionProviderError.other| C2[Subscription2 - not subscribed];
C1 --> |resultHandler error| D[Caller];
C2 --> …
```

fix: Throttle AppSync LimitExceeded errors

---

AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider+Websocket.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProviderResponse.swift
AppSyncRealTimeClientIntegrationTests/AppSyncRealTimeClientFailureTests.swift
AppSyncRealTimeClientTests/ConnectionProvider/AppSyncRealTimeConnection/RealTimeConnectionProviderResponseTests.swift

Refactor the logic for handling an `RealtimeConnectionProviderResponse` over to its extension method called `toConnectionProviderError()`. Originally i was thinking of creating a new enum, but we're already normalizing it over to `ConnectionProviderError` enum (for example, max sub and limit exeeded both map to ConnectionProvider.limitExceeded). Unless we get the entire list of errorTypes to handle and directly decode to, it doesn't seem very useful to have another hand written enum for the error payloads of RealtimeConnectionProviderResponse

fix: refactor error handling

---

AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnectionAsync/RealtimeConnectionProviderAsync+Websocket.swift

This PR added swift async/await concurrency support https://github.com/aws-amplify/aws-appsync-realtime-client-ios/pull/85 renaming the file to RealtimeConnectionProvider**Async**+Websocket over in https://github.com/aws-amplify/aws-appsync-realtime-client-ios/commit/5b9428452bc144ced2bc8c11b59b7b604ce48dd8#diff-9e793df5ee40c091d1d4007f21ceae0c32be2fe1bda4ce651bfa321885c79c14
There were changes in the previous file that was merged in with https://github.com/aws-amplify/aws-appsync-realtime-client-ios/pull/69/files
This PR is to replicate those changes in the new file

fix: rebase RTConnectionProvider+Websocket to Async version

---

AppSyncRealTimeClient/Interceptor/OIDCAuthInterceptor.swift
AppSyncRealTimeClientTests/Interceptor/OIDCAuthInterceptorTests.swift

This PR is part of the efforts to propagate the unauthorized error back to the caller. In the previous PR https://github.com/aws-amplify/aws-appsync-realtime-client-ios/pull/69 we are sure that it works for invalid API keys. When testing with endpoint with user pool auth mode, it would fail with a bad request.
The reason for the bad request is because retrieving the token failed, so the request was not modified before attempting the connection. AppSync will return a bad request indicating that the logic for creating the request was invalid. 
This PR is to ensure even when the user is not signed in, the library will create a valid request, which then gets validated by AppSync as Unauthorized. 
By submitting this pull request, I confirm …

fix: create valid unauthorized request for odic/userpool connections

---

AppSyncRealTimeClient.podspec
AppSyncRealTimeClient/Info.plist
CHANGELOG.md

Ref: similar previous release link https://github.com/aws-amplify/aws-appsync-realtime-client-ios/pull/87

chore: Prep 2.0.0 release

---

AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnectionAsync/RealtimeConnectionProviderAsync+ConnectionInterceptableAsync.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnectionAsync/RealtimeConnectionProviderAsync+MessageInterceptableAsync.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnectionAsync/RealtimeConnectionProviderAsync+StaleConnection.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnectionAsync/RealtimeConnectionProviderAsync+Websocket.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnectionAsync/RealtimeConnectionProviderAsync.swift
AppSyncRealTimeClient/ConnectionProvider/ConnectionProviderFactory.swift
AppSyncRealTimeClient/ConnectionProvider/InterceptableConnectionAsync.swift
AppSyncRealTimeClient/ConnectivityMonitor/ConnectivityMonitor.swift
AppSyncRealTimeClient/ConnectivityMonitor/ConnectivityPath.swift
AppSyncRealTimeClient/Support/TaskQueue.swift
AppSyncRealTimeClientTests/ConnectionProvider/ConnectionProviderHandleErrorTests.swift
Package.swift

#97
Adds platform versions to Package.swift.

fix: supports cross platform builds

---

AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider+Websocket.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider.swift
AppSyncRealTimeClient/Support/AppSyncLogger.swift

#97
Sets versions for each Apple platform.

fix: sets OS versions for os_log

---

AppSyncRealTimeClient.xcodeproj/project.pbxproj
AppSyncRealTimeClient/Interceptor/OIDCAuthInterceptorAsync.swift
AppSyncRealTimeClient/Support/OIDCAuthProviderAsync.swift
Package.swift

add runtime and compiler gates to OIDCAuthInterceptorAsync OIDCAuthProviderAsync and add files to workspace

fix: add runtime and compiler gates to OIDCAuthInterceptorAsync OIDCAuthProviderAsync and add files to workspace

---

AppSyncRealTimeClient/Support/TaskQueue.swift

fix: fixed a bug that prevnted TaskQueue sync method from waiting for the task to complete

fix: fixed a bug that prevnted TaskQueue sync method from waiting for the task to complete

---

AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnectionAsync/RealtimeConnectionProviderAsync.swift
AppSyncRealTimeClient/ConnectionProvider/ConnectionProviderFactory.swift
AppSyncRealTimeClient/Websocket/AppSyncWebsocketProvider.swift
AppSyncRealTimeClient/Websocket/Starscream/StarscreamAdapter.swift
AppSyncRealTimeClientIntegrationTests/AppSyncRealTimeClientAsync/AppSyncRealTimeClientAsyncFailureTests.swift
AppSyncRealTimeClientIntegrationTests/AppSyncRealTimeClientAsync/AppSyncRealTimeClientAsyncIntegrationTests.swift
AppSyncRealTimeClientIntegrationTests/AppSyncRealTimeClientFailureTests.swift
AppSyncRealTimeClientIntegrationTests/AppSyncRealTimeClientIntegrationTests.swift
AppSyncRealTimeClientIntegrationTests/AppSyncRealTimeClientTestBase.swift
AppSyncRealTimeClientIntegrationTests/StarscreamAdapterTests.swift
AppSyncRealTimeClientTests/ConnectionProvider/ConnectionProviderAsync/RealtimeConnectionProviderAsyncTestBase.swift
AppSyncRealTimeClientTests/ConnectionProvider/ConnectionProviderHandleErrorTests.swift
AppSyncRealTimeClientTests/ConnectionProvider/RealtimeConnectionProviderTestBase.swift
AppSyncRealTimeClientTests/Mocks/MockWebsocketProvider.swift
Pods/Pods.xcodeproj/project.pbxproj

These are some changes necessary to allow passing in a URLRequest instead of URL. Because of the change, this will be released as a major version bump v3.0.0.
*Integration Testing*
Swift Package doesn't have the integration test target, which makes sense since we do not produce it as a product for customers. Had to run `pod install` and open the xcworkspace to access the integration test target.

feat: pass URLRequest instead of URL to interfaces

---

Cartfile
Package.swift
Podfile

related: https://github.com/aws-amplify/amplify-flutter/pull/3584

fix: pin starscream to 4.0.4

---

AppSyncRealTimeClient.podspec
AppSyncRealTimeClient/Info.plist
CHANGELOG.md

Bumps version to 3.1.1 and pins starscream dependency to 4.0.4 in the podspec.

chore: Prep 3.1.1 release

---

AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider.swift
AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnectionAsync/RealtimeConnectionProviderAsync.swift
AppSyncRealTimeClient/Websocket/Starscream/StarscreamAdapter.swift

1. [fix(DataStore): Store larger than 32-bit values in Int64 over Int #3367](https://github.com/aws-amplify/amplify-swift/pull/3367)
2. [feat(DataStore): DisableSubscriptions flag for watchOS #3368](https://github.com/aws-amplify/amplify-swift/pull/3368)
3. [fix: watchOS support - disable network monitoring, add client timeout #141](https://github.com/aws-amplify/aws-appsync-realtime-client-ios/pull/141) (You are here)
Network Path Monitoring will return `unsatisified` on watchOS devices since it is considered low-level networking and cannot be used.
This PR avoids using network path monitoring for watchOS so that it will try to attempt to connect if subscribe API is called. This is a critical piece of logic that is required for the …

fix: watchOS support - disable network monitoring, add client timeout

---

.github/workflows/deploy-pods.yml

- remove `build-and-test` step from release workflow as it should have been ran in another triggerred

fix(ci): remove build-and-test workflow from release

---

AppSyncRealTimeClient.podspec
AppSyncRealTimeClient.xcodeproj/project.pbxproj
AppSyncRealTimeClient/Websocket/Starscream/StarscreamAdapter+Delegate.swift
AppSyncRealTimeClient/Websocket/Starscream/StarscreamAdapter.swift
AppSyncRealTimeClientTests/ConnectionProvider/ConnectionProviderStaleConnectionTests.swift
Cartfile
Package.resolved
Package.swift
Podfile
Podfile.lock
Pods/Manifest.lock
Pods/Pods.xcodeproj/project.pbxproj
Pods/Starscream/README.md
Pods/Starscream/Sources/PrivacyInfo.xcprivacy
Pods/Target Support Files/Starscream/ResourceBundle-Starscream_Privacy-Starscream-Info.plist

- Use Starscream 4.0.8, it has privacy manifest that we want to release a version of this package with. 
- Bump iOS min supported version to iOS 12. (iOS 11 is need for starscream 4.0.8, but we are going to iOS 12 to match a consolidate iOS min support bump across the packages).
Ran `pod install` with Starscream 4.0.8, and ran into some build time issues. Issue from https://github.com/daltoniam/Starscream/issues/975 .
Ran tests against iOS and watchOS for both projects opened from Package.swift and xcworkspace. (there was one test that depended connectivity monitor but was not disabled for watchOS)

feat: starscream upgrade to 4.0.8, iOS min 12
